export const TITLE='Elyndeyra Glaciriven Chizeuskia';
export const SUBTITLE='el Mundo de las Siete Torres';
export const CAST=[
 {id:'elendil',name:'Elendil',title:'El Guardián del Rayo',element:'Rayos y tormentas',symbol:'ϟ',color:0x69beff,hex:'#69beff',hair:0x3e281e,cloth:0x19364b,skin:0xc58f72,age:'adult',height:2.04,speed:9.4,companion:'Fénix dorado',power:'Descarga del cielo',description:'Cabello castaño despeinado, barba corta y marcas de rayos azules. Su fénix protege a la familia desde el cielo.',ability:'Carga conductores antiguos con electricidad. En evolución elemental se desplaza con una estela de relámpagos.'},
 {id:'feyre',name:'Feyre',title:'La Guardiana de la Vida',element:'Naturaleza y vida',symbol:'❧',color:0x7eee95,hex:'#7eee95',hair:0xc8a468,cloth:0x245d41,skin:0xd9a888,age:'adult',height:1.91,speed:9,companion:'Dragón negro',power:'Latido del bosque',description:'Cabello rubio largo y rizado, armadura vegetal verde y enredaderas. Un gran dragón negro cuida de ella.',ability:'Devuelve la vida a los árboles secos y hace brotar jardines al utilizar su poder.'},
 {id:'glacial',name:'Glacial',title:'La Hada del Invierno',element:'Hielo y nieve',symbol:'❄',color:0x9feaff,hex:'#9feaff',hair:0xebedf6,cloth:0x20aec2,skin:0xedc8b5,age:'young',height:1.48,speed:9.7,companion:'Osezno blanco de hielo',power:'Flor de escarcha',description:'Pelo blanco corto, ropa turquesa y alas translúcidas heladas. Viaja con un osezno blanco.',ability:'Cristaliza manantiales mágicos. Mantén Salto para planear con sus alas; sobre el agua invoca una plataforma de hielo.'},
 {id:'chispa',name:'Chispa',title:'La Portadora de la Llama',element:'Fuego y calor',symbol:'♨',color:0xff914d,hex:'#ff914d',hair:0x862d17,cloth:0x3e2029,skin:0xd0a080,age:'young',height:1.53,speed:10.1,companion:'Oso de fuego',power:'Corazón de brasa',description:'Cabello largo rojizo oscuro, ropa negra con líneas de lava naranja y oso de fuego.',ability:'Derrite los sellos de hielo y enciende las brasas dormidas sin dañar a la familia.'},
 {id:'zeus',name:'Zeus',title:'El Guardián de la Doble Energía',element:'Electricidad y fuego',symbol:'⟐',color:0xb39aff,hex:'#b39aff',hair:0x984321,cloth:0x272536,skin:0xd0a080,age:'young',height:1.54,speed:11.4,companion:'Osezno negro eléctrico',power:'Doble pulso',description:'Cabello rojizo despeinado, ropa oscura con rayos azules y fuego naranja. Un osezno negro lo acompaña.',ability:'Estabiliza cristales de dos energías. Su evolución combina la velocidad del rayo y la luz del fuego.'},
 {id:'riven',name:'Riven',title:'El Guardián de las Mareas',element:'Agua y corrientes',symbol:'≈',color:0x4acdee,hex:'#4acdee',hair:0xe3eaf5,cloth:0x1c5077,skin:0xe2b69b,age:'young',height:1.5,speed:9.4,companion:'Delfín mágico',power:'Abrazo de la marea',description:'Cabello blanco corto, ropa azul de líneas fluidas y delfín que puede nadar en el aire.',ability:'Llena fuentes secas y controla remolinos de agua. Nada más deprisa que el resto de la familia.'},
 {id:'sky',name:'Sky',title:'La Semilla de las Estrellas',element:'Flores y luz estelar',symbol:'✦',color:0xffd77b,hex:'#ffd77b',hair:0xc67b35,cloth:0x719446,skin:0xe6b591,age:'baby',height:.84,speed:8.6,companion:'Osezno de naturaleza',power:'Risa de las estrellas',description:'Bebé de pelo rizado cobrizo, traje de hojas y flores. Viaja protegido sobre una hoja flotante, con su osezno.',ability:'Despierta las flores de los recuerdos. Conserva su tamaño y aspecto de bebé: su movimiento está protegido por magia.'}
];
export const SITES=[
 {id:'storm',name:'Cumbres del Trueno',x:-340,z:-270,owner:0,task:'Carga los tres conductores del cielo.',noun:'conductor',region:'DOMINIO DEL RAYO',bio:'La piedra escucha las tormentas. Elendil puede devolver la corriente a los tres conductores y despertar este santuario.'},
 {id:'forest',name:'Bosque del Latido',x:-430,z:110,owner:1,task:'Devuelve la vida a los tres árboles.',noun:'árbol dormido',region:'DOMINIO DE LA VIDA',bio:'Las raíces guardan la memoria de Feyre. Solo su magia puede hacer florecer los árboles del círculo antiguo.'},
 {id:'ice',name:'Valle del Hielo Eterno',x:130,z:-430,owner:2,task:'Cristaliza los tres manantiales.',noun:'manantial',region:'DOMINIO DEL INVIERNO',bio:'Los manantiales vibran sin forma. La escarcha de Glacial puede convertirlos en tres cristales que cantan juntos.'},
 {id:'fire',name:'Caldera de Ceniza',x:440,z:-65,owner:3,task:'Derrite el hielo de los tres braseros.',noun:'brasero sellado',region:'DOMINIO DE LA LLAMA',bio:'Un invierno extraño ha apagado los braseros. Chispa debe liberar su fuego y devolver el calor a la caldera.'},
 {id:'dual',name:'Ruinas de la Doble Energía',x:365,z:340,owner:4,task:'Equilibra los tres cristales dobles.',noun:'cristal doble',region:'DOMINIO DE LA CONFLUENCIA',bio:'La electricidad y el fuego buscan un equilibrio. Zeus es el único que puede unirlos sin que se apaguen entre sí.'},
 {id:'water',name:'Lago de los Espejos',x:-270,z:380,owner:5,task:'Llena las tres fuentes de la marea.',noun:'fuente vacía',region:'DOMINIO DE LAS MAREAS',bio:'Los delfines dibujan senderos bajo el agua. Riven puede devolver las corrientes a las fuentes y abrir el santuario.'},
 {id:'garden',name:'El Jardín de Sky',x:45,z:225,owner:6,task:'Despierta las tres flores de los recuerdos.',noun:'flor de los recuerdos',region:'DOMINIO DE LAS ESTRELLAS',bio:'Cada flor guarda una alegría. Sky no necesita palabras: sus destellos estelares pueden despertar todo el jardín.'}
];
export const GAME_VERSION=1;
export const STORE='elyndeyra-3d-adventure-v1';
export const WORLD_HALF=850;
