import * as T from './vendor/engine.js';
import {makeAvatar} from './legacy/avatars.js';
const $=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)];
const status={ready:false,mode:'new',light:'studio',meshTriangles:0,errors:[]};window.labStatus=()=>({...status});
let renderer,scene,camera,controls,high,old,skin,hair,magicGroup,frame=0,last=performance.now(),active=true,dirty=true;
const params={auto:false,magic:true,wire:false},lights=[];
const rand=(()=>{let s=1771;return ()=>{s=(s*1664525+1013904223)>>>0;return s/4294967296}})();
const vec=(x,y,z)=>new T.Vector3(x,y,z);
function addMesh(parent,geo,mat,p=[0,0,0],scale=[1,1,1]){const m=new T.Mesh(geo,mat);m.position.set(...p);m.scale.set(...scale);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
function tube(points,r,mat,parent){const g=new T.TubeGeometry(new T.CatmullRomCurve3(points),Math.max(12,points.length*5),r,5,false);return addMesh(parent,g,mat)}
function taperedHair(points,r){const curve=new T.CatmullRomCurve3(points),segments=9,radial=4,g=new T.TubeGeometry(curve,segments,r,radial,false),a=g.attributes.position;for(let i=0;i<=segments;i++){const p=curve.getPointAt(i/segments),s=Math.pow(1-i/segments,.6)*.92+.08;for(let j=0;j<=radial;j++){let k=i*(radial+1)+j;let v=vec(a.getX(k),a.getY(k),a.getZ(k)).sub(p).multiplyScalar(s).add(p);a.setXYZ(k,v.x,v.y,v.z)}}g.computeVertexNormals();return g}
function scalpPoint(theta,phi,out=0){return vec(-.08+(1.73+out)*Math.sin(theta)*Math.sin(phi),1.75+(2.34+out)*Math.cos(theta),.3+((Math.cos(phi)>0?2.17:2.46)+out)*Math.sin(theta)*Math.cos(phi))}
function makeHair(){hair=new T.Group();high.add(hair);hair.name='Cabello por hebras';const bins=[[],[],[]],capP=[],capI=[],N=64,M=22;for(let j=0;j<=M;j++)for(let i=0;i<=N;i++){const phi=i/N*Math.PI*2,front=Math.max(0,Math.cos(phi)),back=Math.max(0,-Math.cos(phi)),end=1.48-.60*front+.37*back,theta=.01+(j/M)*end,p=scalpPoint(theta,phi,.018);capP.push(p.x,p.y,p.z)}for(let j=0;j<M;j++)for(let i=0;i<N;i++){let k=j*(N+1)+i;capI.push(k,k+N+1,k+1,k+1,k+N+1,k+N+2)}const cap=new T.BufferGeometry();cap.setAttribute('position',new T.Float32BufferAttribute(capP,3));cap.setIndex(capI);cap.computeVertexNormals();const dark=new T.MeshStandardMaterial({color:0x241b16,roughness:.67,side:T.DoubleSide});addMesh(hair,cap,dark);
for(let c=0;c<180;c++){const phi=rand()*Math.PI*2,front=Math.max(0,Math.cos(phi)),back=Math.max(0,-Math.cos(phi)),end=1.29-.40*front+.20*back,theta=.08+Math.sqrt(rand())*end,len=.27+rand()*.37,twist=(phi>Math.PI?-1:1)*(.14+rand()*.24);for(let j=0;j<14;j++){const th=theta+(rand()-.5)*.13,ph=phi+(rand()-.5)*.14,pts=[];for(let k=0;k<5;k++){const t=k/4,p=scalpPoint(th+len*t,ph+twist*t+.08*Math.sin(t*Math.PI*2),.04+.34*Math.sin(t*Math.PI)+t*.12);p.y+=Math.sin(t*Math.PI)*(.14+rand()*.08);p.x+=Math.sin(t*4.5+c)*.035;pts.push(p)}bins[j%3].push(taperedHair(pts,.007+rand()*.010))}}
const colors=[0x211710,0x332316,0x543924];bins.forEach((gs,i)=>{const g=T.mergeGeometries(gs);gs.forEach(x=>x.dispose());addMesh(hair,g,new T.MeshPhysicalMaterial({color:colors[i],roughness:.63,sheen:.35,sheenColor:new T.Color(0x665038),sheenRoughness:.6,specularIntensity:.45}));});}
function makeBeard(geometry){const a=geometry.attributes.position,n=geometry.attributes.normal,idx=geometry.index.array,gs=[],p1=vec(),p2=vec(),p3=vec();for(let tries=0;tries<28000&&gs.length<1400;tries++){const i=Math.floor(rand()*(idx.length/3))*3;const va=idx[i],vb=idx[i+1],vc=idx[i+2];p1.fromBufferAttribute(a,va);p2.fromBufferAttribute(a,vb);p3.fromBufferAttribute(a,vc);let u=rand(),v=rand();if(u+v>1){u=1-u;v=1-v}const p=p1.clone().multiplyScalar(1-u-v).addScaledVector(p2,u).addScaledVector(p3,v);const x=p.x+.1,y=p.y,z=p.z;const jaw=y<.85&&y>-.92&&Math.abs(x)<1.38&&z>1.30;const must=y>.50&&y<.79&&Math.abs(x)<.51&&z>2.1;const lips=Math.abs(x)<.66&&y>.20&&y<.5;const cheek=y>.7&&Math.abs(x)<.76;if((!jaw&&!must)||lips||cheek)continue;const normal=vec().fromBufferAttribute(n,va).normalize();const start=p.clone().addScaledVector(normal,.008),end=p.clone().addScaledVector(normal,.009+rand()*.016).add(vec((rand()-.5)*.014,-.012-rand()*.026,.008));gs.push(taperedHair([start,start.clone().lerp(end,.5).addScaledVector(normal,.013),end],.003+rand()*.004))}if(gs.length){const g=T.mergeGeometries(gs);gs.forEach(x=>x.dispose());addMesh(high,g,new T.MeshStandardMaterial({color:0x312018,roughness:.82})).name='Barba';}}
function irisTexture(){const c=document.createElement('canvas');c.width=c.height=512;const ctx=c.getContext('2d'),im=ctx.createImageData(512,512);for(let y=0;y<512;y++)for(let x=0;x<512;x++){const dx=(x-256)/256,dy=(y-256)/256,r=Math.hypot(dx,dy),a=Math.atan2(dy,dx),stri=Math.sin(a*185+Math.sin(r*43)*.65)+Math.sin(a*297+r*22)*.4;const pupil=r<.32,edge=r>.88,amp=(edge?.4:1)*(.82+stri*.16+rand()*.08);const k=(y*512+x)*4;im.data[k]=pupil?9:Math.min(255,85*amp);im.data[k+1]=pupil?8:Math.min(255,(59+18*(1-r))*amp);im.data[k+2]=pupil?7:Math.min(255,31*amp);im.data[k+3]=255}ctx.putImageData(im,0,0);const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;return t}
const centers=[[-.85,1.59,1.67],[.64,1.585,1.71]];
function eyeCondition(){return `vec2 e1=(vHP.xy-vec2(-.85,1.59))/vec2(.37,.115);vec2 e2=(vHP.xy-vec2(.64,1.585))/vec2(.37,.115);float eyeRegion=min(dot(e1,e1),dot(e2,e2));`;}
function makeEyes(){const tex=irisTexture();for(const [x,y,z] of centers){const sclera=new T.MeshPhysicalMaterial({color:0xe2d8ca,roughness:.3,clearcoat:.8,clearcoatRoughness:.18});const m=addMesh(high,new T.SphereGeometry(1,40,28),sclera,[x,y,z-.10],[.43,.31,.27]);m.name='Ojo';sclera.onBeforeCompile=shader=>{shader.vertexShader='varying vec3 vHP;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\nvHP=(modelMatrix*vec4(position,1.0)).xyz;');shader.fragmentShader='varying vec3 vHP;\n'+shader.fragmentShader;shader.fragmentShader=shader.fragmentShader.replace('#include <clipping_planes_fragment>','#include <clipping_planes_fragment>\n'+eyeCondition()+' if(eyeRegion>1.0) discard;');};sclera.customProgramCacheKey=()=>`sclera-${x}`;const disk=new T.MeshPhysicalMaterial({map:tex,roughness:.28,clearcoat:1,clearcoatRoughness:.08,metalness:0});const iris=addMesh(high,new T.CircleGeometry(.115,64),disk,[x,y,z+.174]);iris.name='Iris';for(const side of[-1,1]){const pts=[];for(let j=0;j<=20;j++){const t=j/20*Math.PI,px=x+.37*Math.cos(t),py=y+side*.116*Math.sin(t);pts.push(vec(px,py,z+.029+Math.sin(t)*.003))}tube(pts,.013,new T.MeshStandardMaterial({color:0x946358,roughness:.58}),high);}}}
function makeMarks(head){magicGroup=new T.Group();high.add(magicGroup);const ray=new T.Raycaster(),core=new T.MeshBasicMaterial({color:0xace6ff}),halo=new T.MeshBasicMaterial({color:0x3a95ff,transparent:true,opacity:.18,depthWrite:false,blending:T.AdditiveBlending});head.updateMatrixWorld(true);function surface(x,y){ray.set(vec(x,y,8),vec(0,0,-1));const hit=ray.intersectObject(head);return hit.length?hit[0].point.clone().addScaledVector(hit[0].face.normal,.024):null}const patterns=[[[ -3.2,-3.4],[-2.93,-3.1],[-3.06,-2.91],[-2.64,-2.77],[-2.48,-2.45],[-2.19,-2.29],[-1.83,-2.05],[-1.63,-1.63]],[[ -2.68,-2.76],[-2.83,-2.3],[-2.47,-2.38],[-2.15,-1.95]],[[ -2.45,-3.63],[-2.1,-3.26],[-2.29,-3.05],[-1.96,-2.87],[-1.81,-2.5],[-1.53,-2.17]],[[ -3.15,-3.05],[-3.46,-2.98],[-3.65,-3.2]],[[ -1.83,-2.5],[-1.53,-2.55],[-1.41,-2.38]]];for(const pat of patterns){const pts=pat.map(p=>surface(...p)).filter(Boolean);if(pts.length>2){tube(pts,.009,core,magicGroup);tube(pts,.032,halo,magicGroup)}}const gold=new T.MeshPhysicalMaterial({color:0xb8a17c,metalness:.92,roughness:.32});const neck=[];for(let i=0;i<26;i++){const t=i/25*Math.PI,p=surface(Math.cos(t)*1.15,-1.85-Math.sin(t)*.9);if(p)neck.push(p.add(vec(0,0,.08)))}if(neck.length>2)tube(neck,.025,gold,high);const pendant=new T.Shape();pendant.moveTo(.04,0);pendant.lineTo(-.13,-.21);pendant.lineTo(-.01,-.19);pendant.lineTo(-.09,-.47);pendant.lineTo(.17,-.15);pendant.lineTo(.04,-.17);pendant.closePath();const pg=new T.ExtrudeGeometry(pendant,{depth:.034,bevelEnabled:true,bevelSize:.012,bevelThickness:.012,bevelSegments:2,steps:1});addMesh(high,pg,gold,[-.08,-2.7,1.1]);}
async function texture(name,color=false){const t=await new T.TextureLoader().loadAsync('./assets/'+name);if(color)t.colorSpace=T.SRGBColorSpace;t.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());return t}
function setLight(mode){dirty=true;status.light=mode;const settings={studio:[0xffedd8,2.4,0xb9daff,1.2,0xffcf97,1.7,.9],storm:[0xc6dbff,1.4,0x3e97ff,3,0x6baeff,2.2,.55],sunset:[0xffb064,3.1,0x9dbdff,.8,0xff7e36,3,.6]};const q=settings[mode]||settings.studio;lights[0].color.set(q[0]);lights[0].intensity=q[1];lights[1].color.set(q[2]);lights[1].intensity=q[3];lights[2].color.set(q[4]);lights[2].intensity=q[5];lights[3].intensity=q[6];all('[data-light]').forEach(b=>b.classList.toggle('active',b.dataset.light===mode));}
function shot(kind){dirty=true;const mobile=innerWidth<700;const views={bust:[mobile?1.5:3,.7,mobile?22:21,0,.35,.4],face:[1.9,1.7,mobile?13.5:12,-.09,1.65,1.1],profile:[11,1.6,10,0,1.35,0]};const v=views[kind]||views.bust;camera.position.set(v[0],v[1],v[2]);controls.target.set(v[3],v[4],v[5]);controls.update();all('[data-shot]').forEach(b=>b.classList.toggle('active',b.dataset.shot===kind));}
function mode(v){dirty=true;renderer.shadowMap.needsUpdate=true;status.mode=v;high.visible=v==='new';old.visible=v==='old';$('#modeTag').textContent=v==='new'?'MODELO PROVISIONAL · NO ES UNREAL':'MODELO ORIGINAL · MISMO RENDERIZADOR';all('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===v));}
function resize(){dirty=true;const w=$('#stage').clientWidth,h=$('#stage').clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();}
async function boot(){scene=new T.Scene();scene.fog=new T.Fog(0x111c2a,26,68);camera=new T.PerspectiveCamera(33,1,.1,110);renderer=new T.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.97;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.shadowMap.autoUpdate=false;renderer.shadowMap.needsUpdate=true;$('#canvasWrap').appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','Visor de modelos 3D: arrastra para girar');controls=new T.OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.08;controls.minDistance=6;controls.maxDistance=33;controls.minPolarAngle=.36;controls.maxPolarAngle=2.1;controls.enablePan=false;controls.autoRotateSpeed=1.15;
for(const [col,intensity,p] of [[0xffeadb,2.4,[-8,7,10]],[0xb9daff,1.2,[8,2,6]],[0xffd7a0,1.7,[1,6,-5]]]){const l=new T.DirectionalLight(col,intensity);l.position.set(...p);scene.add(l);lights.push(l)}const hemi=new T.HemisphereLight(0xc3d5e9,0x44372d,.9);scene.add(hemi);lights.push(hemi);lights[0].castShadow=true;lights[0].shadow.mapSize.set(2048,2048);lights[0].shadow.camera.left=-7;lights[0].shadow.camera.right=7;lights[0].shadow.camera.top=7;lights[0].shadow.camera.bottom=-7;lights[0].shadow.normalBias=.035;
const env=new T.PMREMGenerator(renderer),room=new T.RoomEnvironment();scene.environment=env.fromScene(room,.04).texture;scene.environmentIntensity=.19;room.dispose();env.dispose();
const floor=addMesh(scene,new T.PlaneGeometry(120,120),new T.MeshStandardMaterial({color:0x080e15,roughness:.88,metalness:.2}),[0,-4.18,0]);floor.rotation.x=-Math.PI/2;
const [map,normal]=await Promise.all([texture('Map-COL.jpg',true),texture('Infinite-Level_02_Tangent_SmoothUV.jpg')]);const gltf=await new T.GLTFLoader().loadAsync('./assets/LeePerrySmith.glb');const head=gltf.scene.children.find(x=>x.isMesh);high=new T.Group();scene.add(high);head.geometry=head.geometry.clone();const a=head.geometry.attributes.position;for(let i=0;i<a.count;i++){let x=a.getX(i),y=a.getY(i),z=a.getZ(i);if(y>-.8){const jaw=Math.exp(-Math.pow((y+.25)/.7,2));x=(x+.09)*(.95+.09*jaw)-.09;const nose=Math.exp(-Math.pow((x+.08)/.36,2)-Math.pow((y-1.04)/.55,2));z-=nose*.1;}a.setXYZ(i,x,y,z)}head.geometry.computeVertexNormals();
skin=new T.MeshPhysicalMaterial({map,normalMap:normal,normalScale:new T.Vector2(.42,.42),roughness:.57,metalness:0,specularIntensity:.38,sheen:.04,sheenColor:new T.Color(0x9d5141),color:0xf0dfcf});skin.onBeforeCompile=sh=>{sh.vertexShader='varying vec3 vHP;\n'+sh.vertexShader;sh.vertexShader=sh.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\nvHP=position;');sh.fragmentShader='varying vec3 vHP;\n'+sh.fragmentShader;sh.fragmentShader=sh.fragmentShader.replace('#include <map_fragment>',`#include <map_fragment>
float bx=abs(vHP.x+.09);float by=vHP.y;
float beard=(1.-smoothstep(.0,1.00,by))*smoothstep(1.2,1.85,vHP.z)*smoothstep(-1.02,-.48,by);
float lip=(1.-smoothstep(.48,.69,bx))*smoothstep(.15,.25,by)*(1.-smoothstep(.44,.52,by));
float must=(1.-smoothstep(.40,.62,bx))*smoothstep(.49,.59,by)*(1.-smoothstep(.78,.88,by))*smoothstep(1.9,2.1,vHP.z);
float grain=fract(sin(dot(vHP.xy,vec2(1633.7,772.9)))*43758.5453);
diffuseColor.rgb*=mix(vec3(1.),vec3(.22,.20,.18),clamp((beard*(1.-lip)+must*.85)*(.40+grain*.13),0.,.8));`);};skin.customProgramCacheKey=()=> 'head-prototype-06';head.material=skin;head.castShadow=true;head.receiveShadow=true;high.add(head);makeHair();makeBeard(head.geometry);makeMarks(head);
const av=makeAvatar(0);old=av.root;old.scale.setScalar(11.25);old.position.y=-18.5;old.visible=false;scene.add(old);old.traverse(o=>{if(o.material)o.material.side=T.DoubleSide});
const plinth=addMesh(scene,new T.CylinderGeometry(3.55,3.62,.18,96),new T.MeshStandardMaterial({color:0x141e28,roughness:.44,metalness:.4}),[0,-4.09,-.2]);

resize();shot('bust');setLight('studio');
all('[data-mode]').forEach(b=>b.addEventListener('click',()=>mode(b.dataset.mode)));all('[data-shot]').forEach(b=>b.addEventListener('click',()=>shot(b.dataset.shot)));all('[data-light]').forEach(b=>b.addEventListener('click',()=>setLight(b.dataset.light)));$('#rotate').onchange=e=>controls.autoRotate=e.target.checked;$('#magic').onchange=e=>{dirty=true;magicGroup.visible=e.target.checked;params.magic=e.target.checked};$('#wire').onchange=e=>{dirty=true;params.wire=e.target.checked;for(const group of [high,old])group.traverse(o=>{if(o.isMesh){const ms=Array.isArray(o.material)?o.material:[o.material];ms.forEach(m=>m.wireframe=params.wire)}})};$('#reset').onclick=()=>{shot('bust');setLight('studio');controls.autoRotate=false;$('#rotate').checked=false};$('#capture').onclick=()=>{renderer.render(scene,camera);const c=renderer.domElement;c.toBlob(blob=>{const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='prueba-visual-3D-'+status.mode+'.png';a.click();setTimeout(()=>URL.revokeObjectURL(u),5000)});$('#message').textContent='Captura real del visor, sin retoque ni generación de imagen.'};window.addEventListener('resize',resize);document.addEventListener('visibilitychange',()=>active=!document.hidden);
status.ready=true;status.meshTriangles=head.geometry.index.count/3;$('#loading').style.display='none';window.labTest={shot,mode,setLight,rotate:v=>controls.autoRotate=v,renderer,camera,controls,high,old};renderer.setAnimationLoop(()=>{if(!active)return;const moved=controls.update();if(!moved&&!dirty&&!controls.autoRotate)return;renderer.render(scene,camera);dirty=false;$('#metrics').textContent=`${renderer.info.render.triangles.toLocaleString('es-ES')} triángulos · WebGL 2`;});}
boot().catch(e=>{status.errors.push(e.message);console.error(e);$('#loading').innerHTML='<span>No se ha podido iniciar la prueba 3D.</span><small>'+String(e.message).replaceAll('<','&lt;')+'</small>'});