import * as T from './vendor/three.js';
import {CAST,SITES,TITLE,SUBTITLE,STORE,WORLD_HALF} from './canon.js';
import {buildRealm,heightAt,waterAt,regionAt,mesh,material,GEO,clamp,random} from './realm.js';
import {makeAvatar,makeCompanion} from './avatars.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const canvas=$('#world'),coarse=matchMedia('(pointer:coarse)').matches;
const defaultProgress=()=>({schema:1,character:0,position:{x:-8,z:28},targets:[],shrines:[],echoes:[],lore:[],visited:[],introduced:false,done:false,settings:{quality:'auto',daytime:'sunset',sound:true,lowMotion:matchMedia('(prefers-reduced-motion:reduce)').matches}});
function validateSave(d){if(!d||d.schema!==1)throw Error('El archivo no es una partida compatible.');const s=defaultProgress();s.character=Number.isInteger(d.character)?clamp(d.character,0,6):0;const p=d.position;if(p&&Number.isFinite(p.x)&&Number.isFinite(p.z)){s.position={x:clamp(p.x,-780,780),z:clamp(p.z,-780,780)}}for(const k of['targets','shrines','echoes','lore','visited']){if(Array.isArray(d[k]))s[k]=[...new Set(d[k].filter(a=>typeof a==='string'&&a.length<50))].slice(0,80)}s.targets=s.targets.filter(id=>SITES.some(a=>[0,1,2].some(i=>id===a.id+'-'+i)));s.shrines=s.shrines.filter(id=>SITES.some(a=>a.id===id));s.introduced=!!d.introduced;s.done=s.shrines.length===7&&!!d.done;const o=d.settings||{};for(const k of['quality','daytime'])if(typeof o[k]==='string'&&o[k].length<16)s.settings[k]=o[k];for(const k of['sound','lowMotion'])if(typeof o[k]==='boolean')s.settings[k]=o[k];return s;}
let progress=defaultProgress();try{const s=JSON.parse(localStorage.getItem(STORE));if(s)progress=validateSave(s)}catch{}
let renderer,scene,camera,realm,sun,hemi,magicLight,avatar,companion,particles,clock,initialized=false,playing=false,paused=false,loading=false,time=0,lastFrame=0,uiTime=0,saveTime=0;
const avatars=[],pets=[],player=new T.Vector3(progress.position.x,0,progress.position.z),velocity=new T.Vector3(),keys=new Set();let index=progress.character,vertical=0,grounded=true,camYaw=0,camPitch=.29,camDist=9,energy=100,evolved=false,castUntil=0,castCooldown=0,near=null,trainRide=false,currentRegion='',autoRatio=1,night=0,stepTime=0;
let touchX=0,touchY=0,touchRun=false,jumpHeld=false,walkPhase=0,lookPointer=null,lastPointer={x:0,y:0},resizeTimer,toastTimer,regionTimer,pauseReason='',saveWarning=false;
let effects=[],icePlatforms=[];const desiredCamera=new T.Vector3(),focus=new T.Vector3(),companionGoal=new T.Vector3(),v=new T.Vector3();const colliderGrid=new Map();const CELL=28;
const audio={ctx:null,master:null,
 start(){try{if(!this.ctx){this.ctx=new(window.AudioContext||window.webkitAudioContext)();this.master=this.ctx.createGain();this.master.gain.value=progress.settings.sound?.045:0;this.master.connect(this.ctx.destination);[110,164.81,220,277.18].forEach((freq,i)=>{const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type='sine';o.frequency.value=freq;o.detune.value=i*2;g.gain.value=.05;o.connect(g).connect(this.master);o.start()});}this.ctx.resume().catch(()=>{})}catch{}},
 note(freq=440,dur=.3,volume=.3){if(!this.ctx||!progress.settings.sound)return;const t=this.ctx.currentTime,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type='sine';o.frequency.setValueAtTime(freq,t);o.frequency.exponentialRampToValueAtTime(freq*.6,t+dur);g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(volume,t+.012);g.gain.exponentialRampToValueAtTime(.001,t+dur);o.connect(g).connect(this.master);o.start(t);o.stop(t+dur+.02);},
 chord(){[392,493.88,587.33,783.99].forEach((f,i)=>setTimeout(()=>this.note(f,1.4,.3),i*125));},
 mute(){if(this.master)this.master.gain.setTargetAtTime(progress.settings.sound?(paused?.012:.08):0,this.ctx.currentTime,.15);}
};
class ParticleField{
 constructor(root){this.n=1400;this.cursor=0;this.pos=new Float32Array(this.n*3);this.col=new Float32Array(this.n*3);this.alpha=new Float32Array(this.n);this.sizes=new Float32Array(this.n);this.vel=new Float32Array(this.n*3);this.life=new Float32Array(this.n);this.total=new Float32Array(this.n);this.gravity=new Float32Array(this.n);this.g=new T.BufferGeometry();this.g.setAttribute('position',new T.BufferAttribute(this.pos,3).setUsage(T.DynamicDrawUsage));this.g.setAttribute('pcolor',new T.BufferAttribute(this.col,3).setUsage(T.DynamicDrawUsage));this.g.setAttribute('alpha',new T.BufferAttribute(this.alpha,1).setUsage(T.DynamicDrawUsage));this.g.setAttribute('psize',new T.BufferAttribute(this.sizes,1).setUsage(T.DynamicDrawUsage));this.m=new T.ShaderMaterial({transparent:true,depthWrite:false,blending:T.AdditiveBlending,uniforms:{ratio:{value:1}},vertexShader:'attribute vec3 pcolor;attribute float alpha;attribute float psize;varying vec3 vc;varying float va;uniform float ratio;void main(){vc=pcolor;va=alpha;vec4 mv=modelViewMatrix*vec4(position,1.);gl_PointSize=min(70.,psize*ratio*180./max(1.,-mv.z));gl_Position=projectionMatrix*mv;}',fragmentShader:'varying vec3 vc;varying float va;void main(){float d=length(gl_PointCoord-.5)*2.;float a=pow(max(0.,1.-d),2.);gl_FragColor=vec4(vc,va*a);}' });this.o=new T.Points(this.g,this.m);this.o.frustumCulled=false;root.add(this.o);}
 emit(pos,color,count=30,spread=3,life=1,gravity=1){const c=new T.Color(color);for(let j=0;j<count;j++){const i=this.cursor++%this.n,k=i*3;this.pos[k]=pos.x;this.pos[k+1]=pos.y;this.pos[k+2]=pos.z;this.vel[k]=(Math.random()-.5)*spread;this.vel[k+1]=(Math.random()*.8+.15)*spread;this.vel[k+2]=(Math.random()-.5)*spread;this.life[i]=this.total[i]=life*(.7+Math.random()*.6);this.gravity[i]=gravity;this.col[k]=c.r;this.col[k+1]=c.g;this.col[k+2]=c.b;this.sizes[i]=.13+Math.random()*.34;}}
 update(dt){for(let i=0;i<this.n;i++){if(this.life[i]<=0){this.alpha[i]=0;continue}this.life[i]-=dt;const k=i*3;this.vel[k+1]-=dt*this.gravity[i];this.pos[k]+=this.vel[k]*dt;this.pos[k+1]+=this.vel[k+1]*dt;this.pos[k+2]+=this.vel[k+2]*dt;this.alpha[i]=Math.max(0,this.life[i]/this.total[i]);}for(const k of['position','pcolor','alpha','psize'])this.g.attributes[k].needsUpdate=true;}
}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),4200);}
function save(){if(!initialized)return;progress.character=index;progress.position={x:player.x,z:player.z};try{localStorage.setItem(STORE,JSON.stringify(progress));}catch{if(!saveWarning){saveWarning=true;toast('No se puede guardar en este navegador. Exporta tu partida desde el menú.')}}}
function fillPortraits(){const images=CAST.map(c=>`<img src="assets/${c.id}.webp" alt="${c.name}" title="${c.name}">`).join('');$('#castPreview').innerHTML=images;$('#familyDock').innerHTML=CAST.map((c,i)=>`<button data-character="${i}" aria-label="Controlar a ${c.name}" title="${c.name}: ${c.element}"><img src="assets/${c.id}.webp" alt=""><kbd>${i+1}</kbd><span>${c.name}</span></button>`).join('');$('#questIcons').innerHTML=CAST.map((c,i)=>`<span id="towerIcon${i}" title="${c.name}">${c.symbol}</span>`).join('');if(progress.introduced)$('#savedInfo').textContent=`Continuar partida · ${progress.shrines.length}/7 santuarios · ${progress.echoes.length} ecos · Guardada en este dispositivo`;}
fillPortraits();
async function init(){if(initialized||loading)return;loading=true;$('#start').classList.add('hidden');$('#loading').classList.remove('hidden');audio.start();const load=(f,text)=>{$('#loadingProgress').style.width=f*100+'%';$('#loadingText').textContent=text;};try{
 renderer=new T.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance',preserveDrawingBuffer:false});renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;
 scene=new T.Scene();scene.background=new T.Color(0x90afb9);scene.fog=new T.FogExp2(0x98b4bc,.0018);camera=new T.PerspectiveCamera(55,innerWidth/innerHeight,.12,3200);camera.position.set(-8,10,37);
 hemi=new T.HemisphereLight(0xc5deef,0x62714e,1.6);scene.add(hemi);sun=new T.DirectionalLight(0xffdfaa,3.3);sun.position.set(-90,180,-160);sun.castShadow=true;sun.shadow.mapSize.set(1536,1536);sun.shadow.camera.left=-48;sun.shadow.camera.right=48;sun.shadow.camera.top=48;sun.shadow.camera.bottom=-48;sun.shadow.camera.near=.5;sun.shadow.camera.far=460;sun.shadow.bias=-.00016;sun.shadow.normalBias=.13;scene.add(sun);scene.add(sun.target);magicLight=new T.PointLight(CAST[index].color,0,16,2);scene.add(magicLight);
 load(.03,'Encendiendo la luz del reino…');
 // Procedural environment map, generated once; no external texture services or API calls.
 const envScene=new T.Scene();envScene.add(new T.Mesh(new T.SphereGeometry(80,16,12),new T.MeshBasicMaterial({color:0xa4c4cb,side:T.BackSide})));const top=new T.Mesh(new T.PlaneGeometry(160,160),new T.MeshBasicMaterial({color:0xffe0b4}));top.position.set(0,40,0);top.rotation.x=Math.PI/2;envScene.add(top);const pmrem=new T.PMREMGenerator(renderer);const env=pmrem.fromScene(envScene,.1,.1,150);scene.environment=env.texture;scene.environmentIntensity=.23;pmrem.dispose();envScene.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});
 realm=await buildRealm(scene,load);particles=new ParticleField(scene);
 for(const b of realm.blockers){const key=Math.floor(b.x/CELL)+','+Math.floor(b.z/CELL);if(!colliderGrid.has(key))colliderGrid.set(key,[]);colliderGrid.get(key).push(b)}
 for(let i=0;i<7;i++){avatars[i]=makeAvatar(i);pets[i]=makeCompanion(i);load(.72+i*.025,'Preparando a '+CAST[i].name+'…');await new Promise(r=>setTimeout(r,3));}
 for(const target of realm.targets)if(progress.targets.includes(target.id))realm.activateTarget(target);
 realm.collectibles.forEach(o=>{o.mesh.visible=!progress.echoes.includes(o.id)});realm.shrines.forEach((s,i)=>{if(progress.shrines.includes(s.id)){s.crystal.material.emissiveIntensity=2;s.halo.material.opacity=.8;realm.lightTower(i,true)}});
 player.y=Math.max(heightAt(player.x,player.z),waterAt(player.x,player.z));setCharacter(index,true);quality(progress.settings.quality);setDay(progress.settings.daytime);setupSettings();initialized=true;playing=true;window.__gameReady=true;loading=false;load(1,'La aventura te espera.');await new Promise(r=>setTimeout(r,120));$('#loading').classList.add('hidden');$('#hud').classList.remove('hidden');clock=new T.Clock();lastFrame=performance.now();requestAnimationFrame(frame);updateHUD();
 if(!progress.introduced)toast('Acércate al cristal del centro de la plaza. Mueve con WASD o con la palanca.');
 if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js',{scope:'./'}).catch(()=>{});
 }catch(e){console.error(e);$('#loading').classList.add('hidden');$('#fatalText').textContent=e.message||'Tu navegador no ha podido iniciar WebGL 2.';$('#fatal').classList.remove('hidden');loading=false;}
}
function setCharacter(i,silent=false){if(!avatars[i])return;if(avatar)scene.remove(avatar.root);if(companion)scene.remove(companion.root);index=i;avatar=avatars[i];companion=pets[i];scene.add(avatar.root);scene.add(companion.root);avatar.root.position.copy(player);avatar.root.rotation.y=camYaw+Math.PI;companion.root.position.copy(player).add(new T.Vector3(2,1,3));energy=Math.max(energy,40);evolved=false;magicLight.color.setHex(CAST[i].color);document.documentElement.style.setProperty('--accent',CAST[i].hex);$('#activePortrait').src=`assets/${CAST[i].id}.webp`;$('#activePortrait').alt=CAST[i].name;$('#activeName').textContent=CAST[i].name;$('#activeTitle').textContent=CAST[i].title;$('#powerName').textContent=CAST[i].power;$$('[data-character]').forEach(b=>b.classList.toggle('active',Number(b.dataset.character)===i));if(!silent){particles.emit(player.clone().add(new T.Vector3(0,1,0)),CAST[i].color,45,3.5,1.2,.2);audio.note(392+i*49,.55);toast(`${CAST[i].name} · ${CAST[i].element}`);save();}updateHUD();}
function moveTo(x,z){trainRide=false;player.set(x,Math.max(heightAt(x,z),waterAt(x,z)),z);vertical=0;velocity.set(0,0,0);if(avatar){avatar.root.position.copy(player);companion.root.position.copy(player);}camera.position.set(x+Math.sin(camYaw)*camDist,player.y+5,z+Math.cos(camYaw)*camDist);particles.emit(player.clone().add(new T.Vector3(0,1,0)),CAST[index].color,70,5,1.7,.8);save();}
function nearbyBlockers(x,z){const bx=Math.floor(x/CELL),bz=Math.floor(z/CELL),out=[];for(let ix=-1;ix<=1;ix++)for(let iz=-1;iz<=1;iz++)out.push(...(colliderGrid.get((bx+ix)+','+(bz+iz))||[]));return out;}
function desiredGround(x,z){let y=heightAt(x,z);const w=waterAt(x,z);if(y<w-.35)y=w-.2;for(const p of icePlatforms)if(Math.hypot(x-p.x,z-p.z)<2.8)y=Math.max(y,p.y);return y;}
function updatePlayer(dt){const keyX=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0),keyY=(keys.has('KeyW')||keys.has('ArrowUp')?1:0)-(keys.has('KeyS')||keys.has('ArrowDown')?1:0);let mx=keyX+touchX,my=keyY+touchY;const mag=Math.hypot(mx,my);if(mag>1){mx/=mag;my/=mag;}const moving=mag>.07;const sprint=keys.has('ShiftLeft')||keys.has('ShiftRight')||touchRun;const w=waterAt(player.x,player.z),swimming=heightAt(player.x,player.z)<w-.45&&!icePlatforms.some(p=>Math.hypot(player.x-p.x,player.z-p.z)<2.8);
 let speed=CAST[index].speed*(sprint?1.7:1)*(evolved?1.32:1);if(swimming)speed*=index===5?1.35:index===6?1:.55;
 const dx=-Math.sin(camYaw)*my+Math.cos(camYaw)*mx,dz=-Math.cos(camYaw)*my-Math.sin(camYaw)*mx;velocity.x=T.MathUtils.damp(velocity.x,dx*speed,9,dt);velocity.z=T.MathUtils.damp(velocity.z,dz*speed,9,dt);
 if(trainRide){const p=realm.train.position;player.set(p.x,p.y+5.1,p.z);avatar.root.rotation.y=realm.train.rotation.y;near={kind:'exit-train',name:'Bajar en la estación más cercana'};}else{
 const oldX=player.x,oldZ=player.z;player.x+=velocity.x*dt;player.z+=velocity.z*dt;
 if(Math.hypot(player.x,player.z)>805){player.x=oldX;player.z=oldZ;toast('La bruma protege el borde del reino. Hay otros caminos por explorar.');}
 const y=desiredGround(player.x,player.z),oldY=desiredGround(oldX,oldZ);if(grounded&&y-oldY>Math.max(.65,speed*dt*.92)){player.x=oldX;player.z=oldZ;}
 for(const b of nearbyBlockers(player.x,player.z)){let dx=player.x-b.x,dz=player.z-b.z,d=Math.hypot(dx,dz),min=b.r+.47;if(d<min){if(d<.001){dx=1;dz=0;d=1}player.x=b.x+dx/d*min;player.z=b.z+dz/d*min;}}
 const floor=desiredGround(player.x,player.z);vertical-=dt*(index===2&&jumpHeld&&vertical<0?3.8:22);player.y+=vertical*dt;grounded=player.y<=floor+.03;if(grounded){player.y=floor;vertical=0;}if(index===6&&grounded)player.y=floor+.07;
 if(moving){const target=Math.atan2(dx,dz);let diff=T.MathUtils.euclideanModulo(target-avatar.root.rotation.y+Math.PI,2*Math.PI)-Math.PI;avatar.root.rotation.y+=diff*Math.min(1,dt*11);walkPhase+=dt*(sprint?1.5:1);stepTime+=dt;if(stepTime>.47){stepTime=0;audio.note(swimming?180:75,.075,.13);}}
 }
 avatar.root.position.copy(player);avatar.update(time,dt,moving&&!trainRide,sprint,time<castUntil,evolved,swimming);
 const followY=([0,1,5].includes(index)?(index===1?3.1:2.4):.0);companionGoal.copy(player).add(new T.Vector3(2.2,0,3.8).applyAxisAngle(new T.Vector3(0,1,0),avatar.root.rotation.y-Math.PI));companionGoal.y=Math.max(heightAt(companionGoal.x,companionGoal.z),waterAt(companionGoal.x,companionGoal.z))+followY;if(trainRide)companionGoal.y=player.y+2;const oldPos=companion.root.position.clone();companion.root.position.lerp(companionGoal,Math.min(1,dt*3));v.copy(companionGoal).sub(oldPos);if(v.lengthSq()>.05)companion.root.rotation.y=Math.atan2(v.x,v.z);companion.update(time,dt,v.lengthSq()>.2);
 energy=clamp(energy+dt*(evolved?-4.5:8),0,100);if(energy<=0&&evolved){evolved=false;toast('Tu energía necesita descansar un momento.');}if(evolved&&Math.random()<.5)particles.emit(player.clone().add(new T.Vector3(0,.7,0)),CAST[index].color,2,1.7,.7,-1);
 if(swimming&&index===5&&moving&&Math.random()<.45)particles.emit(player,CAST[index].color,2,2,.5,.4);
 $('#energyFill').style.width=energy+'%';
}
function jump(){if(!playing||paused||trainRide)return;if(grounded){vertical=index===2?9.4:index===6?6.4:8;grounded=false;audio.note(240,.16,.18);}}
function pulseLine(start,end,color){const points=[];for(let i=0;i<13;i++){const t=i/12;points.push(start.clone().lerp(end,t).add(new T.Vector3(i&&i<12?(Math.random()-.5)*.9:0,i&&i<12?(Math.random()-.5)*.8:0,i&&i<12?(Math.random()-.5)*.9:0)))}const g=new T.BufferGeometry().setFromPoints(points),m=new T.LineBasicMaterial({color,transparent:true,opacity:1}),o=new T.Line(g,m);scene.add(o);effects.push({o,g,m,life:.38,total:.38,type:'line'});}
function cast(){if(!playing||paused||time<castCooldown)return;if(energy<17){toast('Deja que la magia se recargue.');return;}energy-=17;castCooldown=time+.72;castUntil=time+.5;const c=CAST[index],start=avatar.handPos();audio.note(index===3?170:490+index*56,.45,.65);let target=null,dist=evolved?28:22;for(const a of realm.targets)if(!a.charged){const d=Math.hypot(a.x-player.x,a.z-player.z);if(d<dist){target=a;dist=d}}
 const dir=new T.Vector3(Math.sin(avatar.root.rotation.y),.08,Math.cos(avatar.root.rotation.y));let end=start.clone().addScaledVector(dir,12);if(target)end.set(target.x,target.y+2,target.z);
 for(let i=0;i<16;i++)particles.emit(start.clone().lerp(end,i/15),index===4&&i%2?0xff943d:c.color,progress.settings.lowMotion?2:6,1.6,.55,.5);
 if([0,4].includes(index))for(let i=0;i<(progress.settings.lowMotion?1:3);i++)pulseLine(start,end,i===2?0xff8f49:c.color);
 particles.emit(end,c.color,progress.settings.lowMotion?20:85,5,1.5,index===5?-1:3);
 const g=new T.RingGeometry(.6,.74,42),m=new T.MeshBasicMaterial({color:c.color,transparent:true,opacity:.72,side:T.DoubleSide,depthWrite:false}),o=mesh(scene,g,m,[end.x,Math.max(heightAt(end.x,end.z),waterAt(end.x,end.z))+.1,end.z],[1,1,1],[-Math.PI/2,0,0]);o.castShadow=false;effects.push({o,g,m,life:1.3,total:1.3,type:'ring'});
 magicLight.position.copy(start);magicLight.intensity=progress.settings.lowMotion?3:18;
 if(target){if(target.owner!==index){toast(`Este ${target.name} necesita a ${CAST[target.owner].name}. Toca su retrato.`);}else{realm.activateTarget(target);if(!progress.targets.includes(target.id))progress.targets.push(target.id);const n=realm.targets.filter(t=>t.site===target.site&&t.charged).length;toast(n===3?'El santuario ha despertado. Acércate al cristal central e interactúa.':`${n}/3 · ${SITES[index].task}`);audio.note(650+n*95,.7,.3);save();}}
 else if(index===2&&heightAt(player.x,player.z)<waterAt(player.x,player.z)){const y=waterAt(player.x,player.z)+.2;const m=material(0xb8e4ec,{metalness:.25,roughness:.18,transparent:true,opacity:.75});const o=mesh(scene,GEO.cyl,m,[player.x,y-.18,player.z],[3,.3,3]);icePlatforms.push({x:player.x,z:player.z,y,life:16,o,m});toast('Una plataforma de hielo sostiene tus pasos durante 16 segundos.');}
 else if(index===1||index===6){const count=18,g=GEO.orb,m=material(index===1?0x74b773:0xf5b9dd,{emissive:c.color,emissiveIntensity:.12}),o=new T.InstancedMesh(g,m,count),d=new T.Object3D();for(let i=0;i<count;i++){const a=i*2.4,r=1+Math.random()*3,x=player.x+Math.sin(a)*r,z=player.z+Math.cos(a)*r;d.position.set(x,heightAt(x,z)+.4,z);d.scale.set(.25,.4,.25);d.updateMatrix();o.setMatrixAt(i,d.matrix)}scene.add(o);effects.push({o,m,life:12,total:12,type:'bloom'});}
 updateHUD();}
function evolution(){if(!playing||paused)return;if(!evolved&&energy<28){toast('Necesitas un poco más de energía para evolucionar.');return;}evolved=!evolved;if(evolved){energy-=12;particles.emit(player.clone().add(new T.Vector3(0,1,0)),CAST[index].color,90,5,2,-.3);audio.chord();toast(`${CAST[index].name}: evolución elemental. Más velocidad y alcance, mientras dure la energía.`);}else toast('Has regresado a tu forma habitual.');}
function checkNear(){if(trainRide){near={kind:'exit-train',name:'Bajar del tren en la Ciudad de las Siete Torres'};return;}near=null;let d=7;const find=(o,kind,range)=>{const v=Math.hypot(player.x-o.x,player.z-o.z);if(v<Math.min(d,range)){near={...o,kind};d=v}};realm.specials.forEach(o=>find(o,o.kind,7));realm.shrines.forEach(o=>find(o,'shrine',7));realm.portals.forEach(o=>find(o,'portal',5));realm.lore.forEach(o=>find(o,'lore',5));}
function interact(){if(!playing||paused)return;if(!near){toast('Acércate a un cristal, un portal, una estela o la estación.');return;}
 if(near.kind==='heart'){
  progress.introduced=true;save();const n=progress.shrines.length;
  if(n===7){progress.done=true;realm.towerLights.forEach((_,i)=>realm.lightTower(i,true));audio.chord();for(let i=0;i<7;i++)particles.emit(new T.Vector3(Math.sin(i)*10,9,Math.cos(i)*10),CAST[i].color,100,14,5,-1);save();showDialog('El mundo vuelve a brillar','EL CORAZÓN DE LAS SIETE TORRES',`<p>Elendil, Feyre, Glacial, Chispa, Zeus, Riven y Sky han despertado los siete santuarios.</p><p>La luz regresa a <b>${TITLE}</b>, ${SUBTITLE}. Podéis seguir explorando, buscar los ecos que faltan, viajar en el tren y fotografiar los reinos.</p><p><b>Aventura completada.</b> La octava estrella guarda una historia para otro día.</p>`);}
  else showDialog('Las siete luces','EL CORAZÓN DE LAS SIETE TORRES',`<p>Siete santuarios guardan el equilibrio del reino. Cada uno necesita el poder de un miembro de la familia.</p><p>Viaja por los caminos o los <b>portales de la plaza</b>. En cada santuario, activa sus <b>tres símbolos con Magia</b> y después toca el cristal central.</p><p>Puedes cambiar de personaje en cualquier momento. <b>El mapa permite viajar directamente a los siete reinos</b>. Cuando todas las torres se iluminen, vuelve aquí.</p><p>Progreso: <b>${n}/7 santuarios.</b></p>`);
 }else if(near.kind==='shrine'){
  const s=near,n=realm.targets.filter(t=>t.site===s.id&&t.charged).length;
  if(progress.shrines.includes(s.id)){toast('Este santuario ya ilumina su torre.');return;}
  if(n<3){showDialog(s.name,CAST[s.owner].title.toUpperCase(),`<p>${s.bio}</p><p><b>${s.task}</b> Cambia a ${CAST[s.owner].name}, acércate a cada símbolo y pulsa Magia.</p><p>Símbolos despiertos: <b>${n}/3.</b></p>`);return;}
  progress.shrines.push(s.id);const real=realm.shrines.find(a=>a.id===s.id);real.crystal.material.emissiveIntensity=2.6;real.halo.material.opacity=.9;realm.lightTower(s.owner,true);energy=100;particles.emit(new T.Vector3(s.x,s.y+5,s.z),CAST[s.owner].color,180,13,4,-1);audio.chord();save();toast(`${s.name} · Santuario despierto. ${progress.shrines.length}/7 torres iluminadas.`);if(progress.shrines.length===7)setTimeout(()=>toast('Las siete torres brillan. Regresa al corazón de la plaza.'),4200);
 }else if(near.kind==='portal'){const s=SITES[near.owner];moveTo(s.x,s.z+22);audio.chord();toast('Has cruzado el portal de '+s.name);}
 else if(near.kind==='lore'){if(!progress.lore.includes(near.id))progress.lore.push(near.id);save();showDialog(near.name,'MEMORIAS DEL REINO',`<p>${near.text}</p><p class="small">Estelas descubiertas: ${progress.lore.length}/7.</p>`);audio.note(620,.7);}
 else if(near.kind==='train'){trainRide=true;toast('A bordo del Tren de las Estrellas. Pulsa Interactuar para bajar en la ciudad.');audio.chord();}
 else if(near.kind==='exit-train'){moveTo(-54,64);toast('El tren te ha dejado junto a la estación.');}
 updateHUD();}
function showDialog(title,tag,text){pause('dialog');$('#dialogTitle').textContent=title;$('#dialogTag').textContent=tag;$('#dialogText').innerHTML=text;$('#dialog').classList.remove('hidden');}
function pause(reason='menu'){if(!initialized&&reason!=='help')return;paused=true;pauseReason=reason;keys.clear();touchX=touchY=0;touchRun=false;jumpHeld=false;$('#stick').style.transform='';lookPointer=null;audio.mute();if(initialized)save();}
function closeOverlay(){for(const id of['menu','map','dialog'])$('#'+id).classList.add('hidden');paused=false;pauseReason='';lastFrame=performance.now();audio.mute();}
function menu(){if(!initialized){$('#menu').classList.remove('hidden');return;}pause();$('#menu').classList.remove('hidden');}
function updateHUD(){if(!realm)return;for(let i=0;i<7;i++)$('#towerIcon'+i).classList.toggle('lit',progress.shrines.includes(SITES[i].id));$('#crystalCount').textContent=`${progress.echoes.length}/42 ecos · ${progress.lore.length}/7 memorias`;
 let s=regionAt(player.x,player.z);if(progress.done){$('#questTitle').textContent='El mundo ha recuperado su luz';$('#questText').textContent='Explora, viaja en el tren y encuentra todos los ecos.';}else if(progress.shrines.length===7){$('#questTitle').textContent='Regresa al corazón de la plaza';$('#questText').textContent='Las siete luces necesitan un último encuentro.';}else if(s&&!progress.shrines.includes(s.id)){const n=realm.targets.filter(t=>t.site===s.id&&t.charged).length;$('#questTitle').textContent=s.name;$('#questText').textContent=n<3?`${CAST[s.owner].name} · ${s.task} ${n}/3`: 'Acércate al cristal central y pulsa Interactuar.';}else if(progress.introduced){$('#questTitle').textContent=`Despierta los santuarios · ${progress.shrines.length}/7`;$('#questText').textContent='Usa los portales de la plaza, abre el mapa o explora los caminos.';}
 const name=s?s.name:'La Ciudad de las Siete Torres';$('#regionName').textContent=Math.hypot(player.x,player.z)<185&&!s?'La Ciudad de las Siete Torres':s?s.name:'Tierras del Horizonte';$('#regionTag').textContent=s?s.region:'EL MUNDO DE LAS SIETE TORRES';const dir=['N','NE','E','SE','S','SO','O','NO'];$('#compass').textContent=dir[Math.round(T.MathUtils.euclideanModulo(camYaw,Math.PI*2)/(Math.PI/4))%8]+(s?' · '+Math.round(Math.hypot(player.x-s.x,player.z-s.z))+' m al santuario':'');
 if(s&&currentRegion!==s.id){currentRegion=s.id;if(!progress.visited.includes(s.id)){progress.visited.push(s.id);showRegion(name);save();}}else if(!s)currentRegion='';
 checkNear();$('#interaction').classList.toggle('hidden',!near);if(near)$('#interactPrompt span').textContent=near.name;}
function showRegion(name){$('#locationToast h2').textContent=name;$('#locationToast').classList.add('visible');clearTimeout(regionTimer);regionTimer=setTimeout(()=>$('#locationToast').classList.remove('visible'),3300);audio.note(620,.7,.2);}
function collect(){for(const o of realm.collectibles){if(!o.mesh.visible)continue;if(Math.hypot(player.x-o.x,player.z-o.z)<2.6){o.mesh.visible=false;progress.echoes.push(o.id);energy=Math.min(100,energy+22);particles.emit(o.mesh.position,0xc4f3df,25,3,1,-.2);audio.note(710,.5,.35);toast(`Eco de luz · ${progress.echoes.length}/42 · Energía recuperada`);save();}}}
function updateCamera(dt){focus.copy(player);focus.y+=index===6?1.4:1.35;const dist=trainRide?17:camDist;desiredCamera.set(focus.x+Math.sin(camYaw)*Math.cos(camPitch)*dist,focus.y+Math.sin(camPitch)*dist,focus.z+Math.cos(camYaw)*Math.cos(camPitch)*dist);desiredCamera.y=Math.max(desiredCamera.y,heightAt(desiredCamera.x,desiredCamera.z)+1.1,waterAt(desiredCamera.x,desiredCamera.z)+.8);camera.position.lerp(desiredCamera,1-Math.exp(-8*dt));camera.lookAt(focus);sun.position.set(player.x-100,player.y+155,player.z-110);sun.target.position.copy(player);realm.sky.position.copy(camera.position);}
let frameCount=0,fpsT=0,currentFPS=60,adaptT=0;
function frame(now){requestAnimationFrame(frame);if(!initialized)return;let raw=(now-lastFrame)/1000;lastFrame=now;if(document.hidden)return;const dt=Math.min(.05,Math.max(.001,raw));if(!paused){time+=dt;updatePlayer(dt);realm.update(time,dt,night);particles.update(dt);magicLight.intensity*=Math.exp(-10*dt);effects=effects.filter(e=>{e.life-=dt;if(e.life<=0){scene.remove(e.o);e.g?.dispose();e.m.dispose();return false;}if(e.type==='ring'){e.o.scale.setScalar(1+(1-e.life/e.total)*7);e.m.opacity=e.life/e.total*.6;}else if(e.type==='line')e.m.opacity=e.life/e.total;return true;});icePlatforms=icePlatforms.filter(p=>{p.life-=dt;if(p.life<=0){scene.remove(p.o);p.m.dispose();return false}p.m.opacity=clamp(p.life,0,1)*.75;return true;});updateCamera(dt);uiTime+=dt;saveTime+=dt;if(uiTime>.22){uiTime=0;updateHUD();collect();}if(saveTime>10){saveTime=0;save();}}
 renderer.render(scene,camera);frameCount++;fpsT+=raw;adaptT+=raw;if(fpsT>2){currentFPS=Math.round(frameCount/fpsT);frameCount=0;fpsT=0;if($('#showFps').checked)$('#fps').textContent=`${currentFPS} fps · ${renderer.info.render.calls} dibujos · ${Math.round(renderer.info.render.triangles/1000)}k triángulos`;else $('#fps').textContent='';}if(adaptT>7&&progress.settings.quality==='auto'){adaptT=0;if(currentFPS<27&&autoRatio>.71){autoRatio=Math.max(.7,autoRatio-.15);resize();}else if(currentFPS>55&&autoRatio<1.2){autoRatio=Math.min(1.2,autoRatio+.05);resize();}}
}
function resize(){if(!renderer)return;const q=progress.settings.quality;const ratio=q==='low'?.82:q==='cinema'?Math.min(devicePixelRatio,2):q==='high'?Math.min(devicePixelRatio,1.5):Math.min(devicePixelRatio,autoRatio);const maxPixels=q==='cinema'?5e6:q==='high'?2.6e6:1.8e6;let effective=Math.min(ratio,Math.sqrt(maxPixels/(innerWidth*innerHeight)));renderer.setPixelRatio(effective);renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();if(particles)particles.m.uniforms.ratio.value=effective;}
function quality(q){if(!['auto','low','high','cinema'].includes(q))q='auto';progress.settings.quality=q;autoRatio=coarse?1:1.2;renderer.shadowMap.enabled=q!=='low';const s=q==='cinema'?2048:q==='high'?1536:1024;if(s!==sun.shadow.mapSize.x){sun.shadow.map?.dispose();sun.shadow.map=null;sun.shadow.mapSize.set(s,s);sun.shadow.needsUpdate=true;}resize();save();}
function setDay(val){if(!['sunset','day','night'].includes(val))val='sunset';progress.settings.daytime=val;night=val==='night'?1:0;sun.color.setHex(night?0x8cbaff:val==='day'?0xfff3db:0xffd59b);sun.intensity=night?.8:val==='day'?3.2:2.75;hemi.intensity=night?.54:1.5;hemi.color.setHex(night?0x6d88c4:0xc4dfed);scene.fog.color.setHex(night?0x15283b:val==='day'?0xaac6cf:0xa5b7b8);renderer.toneMappingExposure=night?.84:1;save();}
function setupSettings(){$('#quality').value=progress.settings.quality;$('#daytime').value=progress.settings.daytime;$('#sound').checked=progress.settings.sound;$('#lowMotion').checked=progress.settings.lowMotion;}
function drawMap(){const ctx=$('#mapCanvas').getContext('2d'),sz=750,scale=sz/1700,tx=x=>(x+850)*scale;ctx.fillStyle='#102630';ctx.fillRect(0,0,sz,sz);for(let z=-850;z<850;z+=30)for(let x=-850;x<850;x+=30){const h=heightAt(x,z),s=regionAt(x,z);ctx.fillStyle=h<waterAt(x,z)?'#1b5365':h>55?'#818f8b':s?['#4d6369','#355344','#8aabba','#675147','#4e4967','#43666b','#56694b'][s.owner]:'#465b50';ctx.globalAlpha=.75;ctx.fillRect(tx(x),tx(z),14,14);}ctx.globalAlpha=1;ctx.strokeStyle='#c6bd974e';ctx.setLineDash([3,6]);for(const s of SITES){ctx.beginPath();ctx.moveTo(tx(0),tx(0));ctx.lineTo(tx(s.x),tx(s.z));ctx.stroke();}ctx.setLineDash([]);ctx.strokeStyle='#b8cfc151';ctx.beginPath();ctx.arc(tx(0),tx(0),565*scale,0,Math.PI*2);ctx.stroke();for(const s of SITES){ctx.fillStyle=CAST[s.owner].hex;ctx.beginPath();ctx.arc(tx(s.x),tx(s.z),10,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#ede1bc';ctx.beginPath();ctx.arc(tx(s.x),tx(s.z),14,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#f8ebcf';ctx.font='bold 12px system-ui';ctx.textAlign='center';ctx.shadowColor='#00121a';ctx.shadowBlur=8;ctx.fillText(CAST[s.owner].name,tx(s.x),tx(s.z)+31);if(progress.shrines.includes(s.id)){ctx.fillStyle='#fff';ctx.font='14px system-ui';ctx.fillText('✓',tx(s.x),tx(s.z)+5)}ctx.shadowBlur=0;}ctx.fillStyle='#e9cd8a';ctx.font='25px Georgia';ctx.textAlign='center';ctx.fillText('✧',tx(0),tx(0)+7);ctx.font='11px system-ui';ctx.fillText('LAS SIETE TORRES',tx(0),tx(0)+24);ctx.save();ctx.translate(tx(player.x),tx(player.z));ctx.rotate(-avatar.root.rotation.y);ctx.fillStyle='#fff';ctx.beginPath();ctx.moveTo(0,8);ctx.lineTo(-5,-6);ctx.lineTo(5,-6);ctx.closePath();ctx.fill();ctx.restore();ctx.fillStyle='#e9d7af';ctx.font='16px Georgia';ctx.fillText('N',sz-35,35);ctx.font='10px system-ui';ctx.fillText('0 ━━━━━ 400 m',95,sz-24);}
function map(){if(!initialized)return;pause('map');drawMap();$('#mapPlaces').innerHTML=`<button class="mapPlace" data-travel="hub"><span>✧</span><div><b>La Ciudad de las Siete Torres</b><small>El corazón de vuestro mundo</small></div><em>Viajar →</em></button>`+SITES.map((s,i)=>`<button class="mapPlace" data-travel="${i}"><span style="color:${CAST[i].hex}">${CAST[i].symbol}</span><div><b>${s.name}</b><small>${CAST[i].name} · ${progress.shrines.includes(s.id)?'Santuario despierto':progress.targets.filter(x=>x.startsWith(s.id+'-')).length+'/3 símbolos'}</small></div><em>Viajar →</em></button>`).join('')+'<p class="small" style="margin-top:12px">Los santuarios se han creado como una aventura del juego. Las formas animales no definidas en el canon no se han inventado: aquí se usa una evolución elemental.</p>';$('#map').classList.remove('hidden');}
function download(blob,name){const a=document.createElement('a');const u=URL.createObjectURL(blob);a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1500);}
function photo(){if(!initialized||paused)return;document.body.classList.add('photo');renderer.render(scene,camera);canvas.toBlob(b=>{document.body.classList.remove('photo');if(b){download(b,`Elyndeyra-Glaciriven-Chizeuskia-${CAST[index].name}.png`);toast('Fotografía del mundo preparada.')}else toast('No se pudo crear la fotografía.');},'image/png');}
function reset(){if(!confirm('¿Reiniciar solo la partida de este juego? No se modifica Mi mundo Mágico v2.'))return;try{localStorage.removeItem(STORE)}catch{}location.reload();}
function clearInput(){keys.clear();touchX=touchY=0;touchRun=false;jumpHeld=false;lookPointer=null;$('#stick').style.transform='';}
$('#play').addEventListener('click',init);$('#guideStart').addEventListener('click',menu);$('#resume').onclick=closeOverlay;$('#menuButton').onclick=menu;$('#mapButton').onclick=map;$('#photoButton').onclick=photo;$('#dialogClose').onclick=closeOverlay;$$('[data-close]').forEach(b=>b.onclick=closeOverlay);$('#familyDock').onclick=e=>{const b=e.target.closest('[data-character]');if(b&&playing&&!paused)setCharacter(Number(b.dataset.character));};$('#interactPrompt').onclick=interact;
$('#castButton').onclick=cast;$('#interactButton').onclick=interact;$('#evolveButton').onclick=evolution;
$('#jumpButton').addEventListener('pointerdown',e=>{e.preventDefault();jumpHeld=true;jump();$('#jumpButton').setPointerCapture(e.pointerId)});$('#jumpButton').addEventListener('pointerup',()=>jumpHeld=false);$('#jumpButton').addEventListener('pointercancel',()=>jumpHeld=false);
$('#runButton').addEventListener('pointerdown',e=>{e.preventDefault();touchRun=true;$('#runButton').setPointerCapture(e.pointerId)});$('#runButton').addEventListener('pointerup',()=>touchRun=false);$('#runButton').addEventListener('pointercancel',()=>touchRun=false);
let stickPointer=null;$('#joystick').addEventListener('pointerdown',e=>{if(paused)return;stickPointer=e.pointerId;$('#joystick').setPointerCapture(e.pointerId);updateStick(e);e.preventDefault();});function updateStick(e){const box=$('#joystick').getBoundingClientRect();let x=e.clientX-box.left-box.width/2,y=e.clientY-box.top-box.height/2;const radius=box.width*.37,d=Math.hypot(x,y);if(d>radius){x*=radius/d;y*=radius/d}touchX=x/radius;touchY=-y/radius;$('#stick').style.transform=`translate(${x}px,${y}px)`;}$('#joystick').addEventListener('pointermove',e=>{if(e.pointerId===stickPointer){updateStick(e);e.preventDefault();}});function releaseStick(e){if(e.pointerId===stickPointer){stickPointer=null;touchX=touchY=0;$('#stick').style.transform='';}}$('#joystick').addEventListener('pointerup',releaseStick);$('#joystick').addEventListener('pointercancel',releaseStick);
canvas.addEventListener('pointerdown',e=>{if(!playing||paused)return;lookPointer=e.pointerId;lastPointer={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);e.preventDefault();});canvas.addEventListener('pointermove',e=>{if(e.pointerId!==lookPointer||paused)return;camYaw-=(e.clientX-lastPointer.x)*.004;camPitch=clamp(camPitch+(e.clientY-lastPointer.y)*.004,-.05,1.14);lastPointer={x:e.clientX,y:e.clientY};});canvas.addEventListener('pointerup',e=>{if(e.pointerId===lookPointer)lookPointer=null;});canvas.addEventListener('pointercancel',()=>lookPointer=null);canvas.addEventListener('wheel',e=>{if(!playing||paused)return;e.preventDefault();camDist=clamp(camDist+e.deltaY*.012,3,20);},{passive:false});canvas.addEventListener('contextmenu',e=>e.preventDefault());
window.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName))return;if(e.code==='Escape'){if(paused)closeOverlay();else menu();return;}if(!playing||paused)return;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Tab'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.repeat)return;if(e.code==='Space'){jumpHeld=true;jump();}if(e.code==='KeyE')interact();if(e.code==='KeyF')cast();if(e.code==='KeyR')evolution();if(e.code==='KeyM')map();if(e.code==='KeyP')photo();if(e.code==='Tab')setCharacter((index+1)%7);if(/^Digit[1-7]$/.test(e.code))setCharacter(Number(e.code.at(-1))-1);});window.addEventListener('keyup',e=>{keys.delete(e.code);if(e.code==='Space')jumpHeld=false;});window.addEventListener('blur',()=>{clearInput();save();});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInput();save();}lastFrame=performance.now();});window.addEventListener('pagehide',save);window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(resize,100);});
$('#quality').onchange=e=>{if(initialized)quality(e.target.value);else progress.settings.quality=e.target.value;};$('#daytime').onchange=e=>{if(initialized)setDay(e.target.value);else progress.settings.daytime=e.target.value;};$('#sound').onchange=e=>{progress.settings.sound=e.target.checked;audio.mute();save();};$('#lowMotion').onchange=e=>{progress.settings.lowMotion=e.target.checked;save();};$('#fullscreen').onclick=()=>{if(document.fullscreenElement)document.exitFullscreen?.();else if(document.documentElement.requestFullscreen)document.documentElement.requestFullscreen().catch(()=>toast('Este navegador no permite activar la pantalla completa.'));else toast('En iPad puedes añadir el juego a la pantalla de inicio desde Safari.');};$('#restart').onclick=reset;
$('#export').onclick=()=>{if(initialized)save();download(new Blob([JSON.stringify(progress,null,2)],{type:'application/json'}),'Elyndeyra-Glaciriven-Chizeuskia-partida.json');};$('#import').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>60000)throw Error('El archivo es demasiado grande.');const d=validateSave(JSON.parse(await file.text()));if(!confirm('¿Sustituir la partida de este dispositivo por la del archivo?'))return;localStorage.setItem(STORE,JSON.stringify(d));location.reload();}catch(err){toast('No se pudo importar: '+err.message);}e.target.value='';};
$('#mapPlaces').onclick=e=>{const b=e.target.closest('[data-travel]');if(!b)return;const id=b.dataset.travel;closeOverlay();if(id==='hub')moveTo(-8,28);else{const s=SITES[Number(id)];if(s)moveTo(s.x,s.z+23);}audio.chord();};$('#mapCanvas').onclick=e=>{const box=e.currentTarget.getBoundingClientRect(),x=(e.clientX-box.left)/box.width*1700-850,z=(e.clientY-box.top)/box.height*1700-850;const s=SITES.find(s=>Math.hypot(x-s.x,z-s.z)<55);if(s){closeOverlay();moveTo(s.x,s.z+23);audio.chord();}};
canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();pause();toast('El móvil ha interrumpido los gráficos. La partida está guardada; recarga para continuar.');});
// Read-only diagnostics for automated tests. Test helpers are available only with ?test=1.
window.gameStatus=()=>({ready:initialized,character:CAST[index].name,position:{x:player.x,y:player.y,z:player.z},shrines:progress.shrines.length,targets:progress.targets.length,echoes:progress.echoes.length,paused,quality:progress.settings.quality,fps:currentFPS,drawCalls:renderer?.info.render.calls,triangles:renderer?.info.render.triangles,gameVersion:1});
if(new URLSearchParams(location.search).get('test')==='1')window.gameTest={travel:i=>{const s=SITES[i];closeOverlay();moveTo(s.x,s.z);setCharacter(i,true);},cast:()=>{castCooldown=0;cast();},interact:()=>{checkNear();interact();},moveTo,setCharacter,showMap:map,day:v=>setDay(v),quality:v=>quality(v),close:closeOverlay,progress:()=>structuredClone(progress),camera:(yaw,pitch,distance)=>{camYaw=yaw;camPitch=pitch;camDist=distance}};
setupSettings();
